# Generated by Django 2.2.6 on 2019-10-29 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_office'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='office',
            table='Office',
        ),
        migrations.AlterModelTable(
            name='organization',
            table='Organization',
        ),
    ]
