# Generated by Django 2.2.6 on 2019-10-29 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191029_1541'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='office',
            table=None,
        ),
        migrations.AlterModelTable(
            name='organization',
            table=None,
        ),
    ]
