# Generated by Django 2.2.6 on 2019-10-29 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191029_1542'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Office',
            new_name='PickupLocation',
        ),
        migrations.AlterModelTable(
            name='pickuplocation',
            table='PickupLocation',
        ),
    ]
