# Generated by Django 2.2.6 on 2019-10-29 18:41

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import lostandfound.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22)),
            ],
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('BAGS', 'BAGS'), ('SUITCASES', 'SUITCASES'), ('BOOKS', 'BOOKS'), ('PHONES', 'CELL PHONES'), ('ELECTRONICS', 'ELECTRONICS & ACCESSORIES'), ('CLOTHING', 'CLOTHING & ACCESSORIES'), ('JEWELRY', 'JEWELRY'), ('MUSIC INSTRUMENTS', 'MUSIC INSTRUMENTS')], max_length=30)),
                ('date_time', models.DateTimeField()),
                ('location', djongo.models.fields.EmbeddedModelField(model_container=lostandfound.models.GeoLocation, null=True)),
                ('features', models.TextField(max_length=150)),
            ],
            options={
                'db_table': 'lostitem',
            },
        ),
        migrations.CreateModel(
            name='PickupLocation',
            fields=[
                ('address', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('office', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('BAGS', 'BAGS'), ('SUITCASES', 'SUITCASES'), ('BOOKS', 'BOOKS'), ('PHONES', 'CELL PHONES'), ('ELECTRONICS', 'ELECTRONICS & ACCESSORIES'), ('CLOTHING', 'CLOTHING & ACCESSORIES'), ('JEWELRY', 'JEWELRY'), ('MUSIC INSTRUMENTS', 'MUSIC INSTRUMENTS')], max_length=30)),
                ('date_time', models.DateTimeField()),
                ('location', djongo.models.fields.EmbeddedModelField(model_container=lostandfound.models.GeoLocation, null=True)),
                ('features', models.TextField(max_length=150)),
                ('image', models.ImageField(upload_to='')),
                ('pickup_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lostandfound.PickupLocation')),
            ],
            options={
                'db_table': 'founditem',
            },
        ),
    ]
