# Generated by Django 2.2.6 on 2019-11-01 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_color', models.CharField(max_length=15)),
                ('feature_size', models.CharField(max_length=15)),
                ('feature_category', models.CharField(max_length=15)),
                ('date', models.DateField(auto_now_add=True)),
                ('location_lat', models.DecimalField(decimal_places=10, max_digits=19)),
                ('location_long', models.DecimalField(decimal_places=10, max_digits=19)),
                ('description', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lostandfound.Item')),
                ('image', models.ImageField(upload_to='')),
                ('pickup_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.PickupLocation')),
            ],
            bases=('lostandfound.item',),
        ),
    ]
