# Generated by Django 2.2.6 on 2019-10-30 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('BAGS', 'BAGS'), ('SUITCASES', 'SUITCASES'), ('BOOKS', 'BOOKS'), ('PHONES', 'CELL PHONES'), ('ELECTRONICS', 'ELECTRONICS & ACCESSORIES'), ('CLOTHING', 'CLOTHING & ACCESSORIES'), ('JEWELRY', 'JEWELRY'), ('MUSIC INSTRUMENTS', 'MUSIC INSTRUMENTS')], max_length=30)),
                ('date_time', models.DateTimeField()),
                ('description', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PickupLocation',
            fields=[
                ('address', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('office', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('BAGS', 'BAGS'), ('SUITCASES', 'SUITCASES'), ('BOOKS', 'BOOKS'), ('PHONES', 'CELL PHONES'), ('ELECTRONICS', 'ELECTRONICS & ACCESSORIES'), ('CLOTHING', 'CLOTHING & ACCESSORIES'), ('JEWELRY', 'JEWELRY'), ('MUSIC INSTRUMENTS', 'MUSIC INSTRUMENTS')], max_length=30)),
                ('date_time', models.DateTimeField()),
                ('description', models.TextField(max_length=150)),
                ('image', models.ImageField(upload_to='')),
                ('pickup_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lostandfound.PickupLocation')),
            ],
        ),
    ]
