# Generated by Django 2.2.6 on 2019-10-29 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeoLocation',
        ),
    ]
