# Generated by Django 2.2.6 on 2019-11-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0002_auto_20191031_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
