# Generated by Django 2.2.6 on 2019-10-29 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0002_delete_geolocation'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='founditem',
            table=None,
        ),
        migrations.AlterModelTable(
            name='lostitem',
            table=None,
        ),
    ]
