# Generated by Django 2.2.6 on 2019-10-29 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0003_auto_20191029_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='founditem',
            old_name='features',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='lostitem',
            old_name='features',
            new_name='description',
        ),
    ]
